version: "3.3"

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    restart: "no"
    container_name: elasticsearch_1
    environment:
      discovery.type: "single-node"
      path.data: "/var/lib/elasticsearch"
      path.logs: "/var/log/elasticsearch"
      cluster.name: "my-cluster"
      node.name: "my-node-1"
      network.host: "0.0.0.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ../elasticsearch1/data:/var/lib/elasticsearch
      - ../elasticsearch1/logs:/var/log/elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - my_network

  kibana:
    image:  docker.elastic.co/kibana/kibana:7.5.2
    restart: "no"
    container_name: kibana_1
    ports:
      - "5601:5601" 
    depends_on:
      - elasticsearch1  
    volumes:
      - ../kibana/config:/usr/share/kibana/config
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - my_network

  cerebro:
    image: yannart/cerebro
    restart: "no"
    container_name: cerebro_1
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch1
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - my_network

networks:
  my_network: 